name = "viet"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
[[routes]]
pattern = "viet.meong.us.kg"
custom_domain = true
[vars]
PROXYIP = "103.45.232.251:50678"
UUID = "862a1ca5-eb90-400a-8b3c-df88f85bee13"
