name = "pmi"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
[[routes]]
pattern = "pmi.jembot.us.kg"
custom_domain = true
[vars]
PROXYIP = "103.6.207.108:8080"
UUID = "862a1ca5-eb90-400a-8b3c-df88f85bee13"
