name = "vless"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
[[routes]]
pattern = "jembot.us.kg"
custom_domain = true
[vars]
PROXYIP = "35.219.15.90:443"
UUID = "862a1ca5-eb90-400a-8b3c-df88f85bee13"
