name = "cagayan"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
[[routes]]
pattern = "cagayan.jembot.us.kg"
custom_domain = true
[vars]
PROXYIP = "203.194.112.119:8443"
UUID = "862a1ca5-eb90-400a-8b3c-df88f85bee13"
