name = "vip"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
[[routes]]
pattern = "vip.meong.us.kg"
custom_domain = true
[vars]
PROXYIP = "172.232.239.151:587"
UUID = "862a1ca5-eb90-400a-8b3c-df88f85bee13"
